### ISSUE TITLE
Test Issues of 116

### ISSUE THREAD

**Issue by SamwellACE92** [reactive-firewall/Pocket-PiAP#118]
![2101939A-B69A-44C8-9956-B7B05A6DEB50](https://user-images.githubusercontent.com/45780487/58296988-d7251000-7d8a-11e9-9586-22836f4b421b.png)
![4462EF79-BB67-4045-BC8C-9A70032C3ACC](https://user-images.githubusercontent.com/45780487/58296989-d7251000-7d8a-11e9-9533-ee103bd6a065.png)
PiAP 0.4.0
Python version: All tested versions
OS type: Ubuntu 14.04.5
`piaplib` version: 0.4.0-2019
https://travis-ci.org/reactive-firewall/Pocket-PiAP/jobs/465445057

**Comment by reactive-firewall** [comment]
Screen-shots are unclear. What is the bug? Please describe.
