### ISSUE TITLE
Missing Version Info in CI

### ISSUE THREAD

**Issue by SamwellACE92** [reactive-firewall/Pocket-PiAP#119]
In regards to issue #118 , the Python and piaplib version info was not obtainable from the logs and needed to be provided by Mr. Walls. Those version numbers should be present to ensure proper bug reports can be made.

**Comment by reactive-firewall** [comment]
Build logs on CI like travis should indeed output basic info about each test run, namely:

 - Python version:
  `python3 --version || python --version`
 -  OS type
  `uname -a`
- `piaplib` version:
 `python3 -m pocket version --verbose --all`

**Comment by reactive-firewall** [comment]
Closed by supersession (version 0.4.2 staged and supersedes version 0.4.1)

**Comment by reactive-firewall** [comment]
see #124 staging
